from bs4 import BeautifulSoup
import requests

url_host = 'http://lz.ganji.com'
start_url = 'http://lz.ganji.com/wu/'
channel_list = []
def get_channel(url):

    web_data = requests.get(url)
    soup = BeautifulSoup(web_data.text,'lxml')
    links = soup.select('dl > dd > a')
    for link in links:
        page_url = url_host + link.get('href')
        channel_list.append(page_url)



get_channel(start_url)

"""
channel_list = [

    
    http://lz.ganji.com/iphone/
    http://lz.ganji.com/ipodTouch/
    http://lz.ganji.com/iphone-iphone-4s/
    http://lz.ganji.com/mi-hongmi/
    http://lz.ganji.com/sanxingshouji-galaxy-s-iv/
    http://lz.ganji.com/sanxingshouji-galaxy-note-iii/
    http://lz.ganji.com/pingguo/
    http://lz.ganji.com/lianxiang/
    http://lz.ganji.com/thinkpad/
    http://lz.ganji.com/suoni/
    http://lz.ganji.com/daier/
    http://lz.ganji.com/huashuo/
    http://lz.ganji.com/ershoubijibendiannao/_New+iPad/
    http://lz.ganji.com/ershoubijibendiannao/_%E4%B9%90Pad/
    http://lz.ganji.com/psv/
    http://lz.ganji.com/shuma/_%E4%BD%B3%E8%83%BD/
    http://lz.ganji.com/shuma/_%E5%B0%BC%E5%BA%B7/
    http://lz.ganji.com/shuangrenchuang/
    http://lz.ganji.com/dianfengshan/
    http://lz.ganji.com/tongche/
    http://lz.ganji.com/qunzi/
    http://lz.ganji.com/fangshaishuang/
    http://lz.ganji.com/iphone/
    http://lz.ganji.com/nokia/
    http://lz.ganji.com/htc/
    http://lz.ganji.com/sanxingshouji/
    http://lz.ganji.com/motorola/
    http://lz.ganji.com/suoniailixin/
    http://lz.ganji.com/shouji/p1/
    http://lz.ganji.com/shouji/b1000e1500/
    http://lz.ganji.com/lanyaerji/
    http://lz.ganji.com/shoujike/
    http://lz.ganji.com/shoujidianchi/
    http://lz.ganji.com/chongdianqi/
    http://lz.ganji.com/pingbandiannao/z1/
    http://lz.ganji.com/bijibendiannao/
    http://lz.ganji.com/shangwangben/
    http://lz.ganji.com/ershoubijibendiannao/_%E6%B8%B8%E6%88%8F%E6%9C%BA/
    http://lz.ganji.com/ershoubijibendiannao/_%E5%95%86%E5%8A%A1%E6%9C%AC/
    http://lz.ganji.com/bijibendiannao/b0e500/
    http://lz.ganji.com/bijibendiannao/p3/
    http://lz.ganji.com/ershoubijibendiannao/p4/
    http://lz.ganji.com/taishidiannaozhengji/
    http://lz.ganji.com/yitiji/
    http://lz.ganji.com/fuwuqi/
    http://lz.ganji.com/xianka/
    http://lz.ganji.com/cpu/
    http://lz.ganji.com/yingpan/
    http://lz.ganji.com/xianshiqi/
    http://lz.ganji.com/neicun/
    http://lz.ganji.com/zhuban/
    http://lz.ganji.com/wuxianluyouqi/
    http://lz.ganji.com/yidongyingpan/
    http://lz.ganji.com/diannaoyinxiang/
    http://lz.ganji.com/dayinji/
    http://lz.ganji.com/3gwangka/
    http://lz.ganji.com/danfanxiangji/
    http://lz.ganji.com/dandianxiangji/
    http://lz.ganji.com/jingtou/
    http://lz.ganji.com/shumashexiangji/
    http://lz.ganji.com/yueqiyinxiang/
    http://lz.ganji.com/ipodTouch/
    http://lz.ganji.com/psp/
    http://lz.ganji.com/ps3/
    http://lz.ganji.com/zhanghaozhuangbei/
    http://lz.ganji.com/chongzhidianka/
    http://lz.ganji.com/qqhao/z1/
    http://lz.ganji.com/chuangdian/
    http://lz.ganji.com/guizi/
    http://lz.ganji.com/zhuoyi/
    http://lz.ganji.com/shafachaji/
    http://lz.ganji.com/rirongbaihuo/
    http://lz.ganji.com/bangongjiaju/
    http://lz.ganji.com/jiaju/_%E6%90%AC%E5%AE%B6/
    http://lz.ganji.com/jiaju/p1/
    http://lz.ganji.com/dianshi/
    http://lz.ganji.com/bingxiang/
    http://lz.ganji.com/kongtiao/
    http://lz.ganji.com/reshuiqi/
    http://lz.ganji.com/xiyiji/
    http://lz.ganji.com/diancilu/
    http://lz.ganji.com/weibolu/
    http://lz.ganji.com/doujiangji/
    http://lz.ganji.com/yueqiyinxiang/
    http://lz.ganji.com/zixingchemaimai/
    http://lz.ganji.com/diandongche/
    http://lz.ganji.com/motuoche/
    http://lz.ganji.com/sanlunche/
    http://lz.ganji.com/anmobaojian/
    http://lz.ganji.com/chuangshangyongpin/
    http://lz.ganji.com/zhuangshibaishe/
    http://lz.ganji.com/yingerche/
    http://lz.ganji.com/niuniuche/
    http://lz.ganji.com/xuebuche/
    http://lz.ganji.com/ertonganquanzuoyi/
    http://lz.ganji.com/yingerchuang/z1/
    http://lz.ganji.com/niaobushi/
    http://lz.ganji.com/naifen/
    http://lz.ganji.com/tongche/
    http://lz.ganji.com/tongzhuang/
    http://lz.ganji.com/wanju/
    http://lz.ganji.com/qunzi/
    http://lz.ganji.com/gaogenxie/
    http://lz.ganji.com/liangxie/
    http://lz.ganji.com/shoubiao/
    http://lz.ganji.com/shipin/
    http://lz.ganji.com/lvxingxiang/
    http://lz.ganji.com/danjianbao/
    http://lz.ganji.com/shuangjianbao/
    http://lz.ganji.com/shoutibao/
    http://lz.ganji.com/xiangshui/
    http://lz.ganji.com/fangshaishuang/
    http://lz.ganji.com/huazhuangpin/
    http://lz.ganji.com/hufupin/
    http://lz.ganji.com/paobuji/
    http://lz.ganji.com/yaling/
    http://lz.ganji.com/yumaoqiuqicai/
    http://lz.ganji.com/shoufuji/z1/
    http://lz.ganji.com/jita/
    http://lz.ganji.com/gangqin/
    http://lz.ganji.com/dianziqin/
    http://lz.ganji.com/zhuanyejishushuji/
    http://lz.ganji.com/kaoshijiaofu/
    http://lz.ganji.com/xiaoshuowenxue/
    http://lz.ganji.com/jiguangyitiji/
    http://lz.ganji.com/dayinji/
    http://lz.ganji.com/bangongzhuo/
    http://lz.ganji.com/diannaozhuo/
    http://lz.ganji.com/huojiazhanjia/z1/
    http://lz.ganji.com/jichuang/
    http://lz.ganji.com/fengrenji/
    http://lz.ganji.com/fadianji/
    http://lz.ganji.com/shipinjiagongshebei/
    http://lz.ganji.com/gongjuwujin/
    http://lz.ganji.com/nongyongjixie/
    http://lz.ganji.com/tuolaji/
    http://lz.ganji.com/shucaishuiguo/
    http://lz.ganji.com/miaomu/
    http://lz.ganji.com/qitalipinzhuanrang/
    http://lz.ganji.com/kalei/
    http://lz.ganji.com/shoubiao/
    http://lz.ganji.com/jiu/
    http://lz.ganji.com/chaye/
    http://lz.ganji.com/shougongshizixiu/
    http://lz.ganji.com/youpiao/
    http://lz.ganji.com/guwan/
    http://lz.ganji.com/jinyinzhuyu/
    http://lz.ganji.com/gongyipin/
    http://lz.ganji.com/dongchongxiacao/
    http://lz.ganji.com/kafeizhuanrang/
    http://lz.ganji.com/haishen/
    http://lz.ganji.com/rencan/
    http://lz.ganji.com/fengmi/
    http://lz.ganji.com/anmobaojian/z1/
    http://lz.ganji.com/zibubaojian/z2/
    http://lz.ganji.com/bawanwujian/
    http://lz.ganji.com/zangao/
    http://lz.ganji.com/taidixiong/
    http://lz.ganji.com/jinmao/
    http://lz.ganji.com/hashiqi/
    http://lz.ganji.com/dog/
    http://lz.ganji.com/chongwupeizhong/
    http://lz.ganji.com/mao/
    http://lz.ganji.com/longmao/
    http://lz.ganji.com/jinli/
    http://lz.ganji.com/yingwu/
    http://lz.ganji.com/cangshu/
    http://lz.ganji.com/qitaxiaochong/_%E5%85%94%E5%AD%90/
    http://lz.ganji.com/gouwuka/
    http://lz.ganji.com/daijinquan/
    http://lz.ganji.com/jianshenka/
    http://lz.ganji.com/youyongka/
    http://lz.ganji.com/dianyingpiao/
    http://lz.ganji.com/jingdianmenpiao/
    http://lz.ganji.com/yanchanghuimenpiao/
    http://lz.ganji.com/tiyusaishi/
    http://lz.ganji.com/chuangdian/
    http://lz.ganji.com/guizi/
    http://lz.ganji.com/zhuoyi/
    http://lz.ganji.com/shafachaji/
    http://lz.ganji.com/zixingchemaimai/
    http://lz.ganji.com/diandongche/
    http://lz.ganji.com/motuoche/
    http://lz.ganji.com/iphone/
    http://lz.ganji.com/nokia/
    http://lz.ganji.com/htc/
    http://lz.ganji.com/sanxingshouji/
    http://lz.ganji.com/motorola/
    http://lz.ganji.com/shouji/_%E5%B0%8F%E7%B1%B3/
    http://lz.ganji.com/shouji/_%E9%AD%85%E6%97%8F/
    http://lz.ganji.com/bangongjiaju/
    http://lz.ganji.com/jiguangyitiji/
    http://lz.ganji.com/dayinji/z1/
    http://lz.ganji.com/shipinjiagongshebei/
    http://lz.ganji.com/shengchanjiamengshebei/
    http://lz.ganji.com/jichuang/
    http://lz.ganji.com/tuolaji/
    http://lz.ganji.com/dianshi/
    http://lz.ganji.com/bingxiang/
    http://lz.ganji.com/kongtiao/
    http://lz.ganji.com/reshuiqi/
    http://lz.ganji.com/xiyiji/
    http://lz.ganji.com/diancilu/
    http://lz.ganji.com/weibolu/
    http://lz.ganji.com/yueqiyinxiang/
    http://lz.ganji.com/pingbandiannao/z1/
    http://lz.ganji.com/ershoubijibendiannao/z1/_%E8%8B%B9%E6%9E%9C/
    http://lz.ganji.com/ershoubijibendiannao/z1/_%E8%81%94%E6%83%B3/
    http://lz.ganji.com/ershoubijibendiannao/z1/_Thinkpad/
    http://lz.ganji.com/ershoubijibendiannao/z1/_%E7%B4%A2%E5%B0%BC/
    http://lz.ganji.com/ershoubijibendiannao/z1/_%E6%88%B4%E5%B0%94/
    http://lz.ganji.com/ershoubijibendiannao/z1/_%E5%8D%8E%E7%A1%95/
    http://lz.ganji.com/ershoubijibendiannao/z1/_%E6%83%A0%E6%99%AE/
    http://lz.ganji.com/yueqi/
    http://lz.ganji.com/yinxiang/
    http://lz.ganji.com/yundongqicai/
    http://lz.ganji.com/tongche/
    http://lz.ganji.com/tongzhuang/
    http://lz.ganji.com/yingerche/
    http://lz.ganji.com/yingerchuang/z1/
    http://lz.ganji.com/niaobushi/
    http://lz.ganji.com/wanju/
    http://lz.ganji.com/naifen/
    http://lz.ganji.com/taishidiannaozhengji/
    http://lz.ganji.com/xianka/
    http://lz.ganji.com/cpu/
    http://lz.ganji.com/yingpan/
    http://lz.ganji.com/luyouqi/
    http://lz.ganji.com/3gwangka/
    http://lz.ganji.com/shoucangpin/
    http://lz.ganji.com/qitalipinzhuanrang/
    http://lz.ganji.com/baojianpin/
    http://lz.ganji.com/xiaofeika/
    http://lz.ganji.com/fushi/
    http://lz.ganji.com/xiangbao/
    http://lz.ganji.com/xuemao/
    http://lz.ganji.com/shoubiao/
    http://lz.ganji.com/shipin/
    http://lz.ganji.com/huazhuangpin/
    http://lz.ganji.com/hufupin/
    http://lz.ganji.com/shumaxiangji/
    http://lz.ganji.com/shumashexiangji/
    http://lz.ganji.com/youxiji/
    http://lz.ganji.com/suishenting/
    http://lz.ganji.com/yidongcunchu/
    http://lz.ganji.com/zibubaojian/z2/
    http://lz.ganji.com/anmobaojian/z1/
    http://lz.ganji.com/bawanwujian/

]

"""
